# SPDX-License-Identifier: LGPL-3.0-only
# Turns the OptiLithium icon's "OF" into "OL".
#
# WHY NOT EDIT THE LETTERS DIRECTLY. The icon is flat-shaded art: the "F" is three axis-aligned rectangles of one
# colour on a transparent background, so changing F to L is not a font edit - it is exact pixel operations.
#
# WHAT AN "L" IS HERE. The F consists of a top bar, a middle bar, and a stem. An L has NO top bar: it is a stem
# that runs the full height plus a foot at the bottom. So the patch is
#
#     * delete the top bar and the middle bar   (the two arms that make it an F)
#     * keep and COMPLETE the stem, then add the foot
#
# An earlier version of this script kept the top bar, on the reasoning that an "L" starts with a vertical stroke
# at the top - which is true of the letter but wrong about this drawing: in this drawing that rectangle IS the
# F's upper arm, and leaving it in produces something that is neither an F nor an L.
#
# Geometry, MEASURED from the source (not guessed):
#
#   second glyph, x 73..108
#   top bar     y 39..49,  x 74..108   (35 wide)   DELETE
#   stem        x 74..87   (14 solid; x73 is an alpha-51 anti-aliased left edge)   KEEP, extended to y38..85
#   middle bar  y 56..66,  x 74..105   (32 wide)   DELETE
#   foot        y 74..85,  x 74..105   (32 wide)   ADD
#
# Rows/columns for the new parts are chosen to agree with the art, not invented:
#   * the stem runs y 38..85 so the L is exactly as tall as the O (O occupies y 38..85);
#   * the foot is 32 wide - the width the original middle bar already used, so the foot matches a proportion
#     that exists in this design rather than introducing a new one, and it leaves the gap to the O intact;
#   * the foot keeps the bars' ~11px thickness (ideal rectangle y 74..85 with the edge pixels half-covered).
#
# Every affected band is CLEARED COMPLETELY (alpha 0) before anything is drawn, because the bars carry
# anti-aliased edges (alpha 1..254). Deleting only the fully opaque pixels would leave a ghost outline of the old
# arms, so new anti-aliasing is generated by coverage instead.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File make-icon-ol.ps1 -Source <icon.png> -Output <icon-ol.png>
param(
	# The icon to rewrite. Defaults to the copy on the Desktop.
	[string]$Source = 'C:\Users\kynar\Desktop\icon.png',
	[string]$Output = 'C:\Users\kynar\Desktop\icon-ol.png'
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

if (-not (Test-Path $Source)) { throw "no source icon at $Source" }

# The single fill colour of the art, sampled from the source rather than hard-coded, so a recoloured icon still
# round-trips through this script.
$probe = New-Object System.Drawing.Bitmap($Source)
$fill = $probe.GetPixel(80, 44)
$probe.Dispose()
if ($fill.A -eq 0) { throw "the pixel used to sample the fill colour is transparent - the icon layout changed" }
Write-Host "[icon] fill colour: RGBA($($fill.R),$($fill.G),$($fill.B),$($fill.A))"

$src = New-Object System.Drawing.Bitmap($Source)
$w = $src.Width
$h = $src.Height

# Clone(), not Graphics.DrawImageUnscaled(): the drawing path routes the pixels through a colour transform and
# shifts them by one step in a channel here and there (G 161 became 160 on 26 pixels of the untouched "O"). The
# patch is meant to touch the second glyph and NOTHING else, so Clone's exact copy is what is wanted.
$work = $src.Clone()
$src.Dispose()

# --- 1. delete the two arms, and ONLY the arms ---
#
# The erasing rectangle must start where the arm stops being the STEM. Clearing an arm's full width in one go
# (x 74..108) also wipes the stem across those rows and cuts the glyph in half - an earlier version of this script
# produced exactly that, so the columns are listed explicitly:
#
#   x 88..108  -> the arm to the right of the stem. Cleared.
#   x 74..87   -> the stem. NOT touched; the arm and the stem are one flat colour, so once the overhang is gone
#                 what remains there is already the stem.
#
# The row ranges are the arms' solid rows widened by one on each side, to take the anti-aliased rows with them.
$deleteBands = @(
	@(38, 50),   # top bar's solid rows are 39..49
	@(55, 67)    # middle bar's solid rows are 56..66
)
foreach ($band in $deleteBands) {
	for ($y = $band[0]; $y -le $band[1]; $y++) {
		for ($x = 88; $x -le 108; $x++) {
			$work.SetPixel($x, $y, [System.Drawing.Color]::FromArgb(0, 0, 0, 0))
		}
	}
}

# --- 2. draw the new parts, with anti-aliasing generated by coverage ---
#
# A pixel is filled in proportion to how much of it the ideal rectangle covers, and its alpha is scaled by that
# coverage. That is what the original art looks like: flat interior, soft edge. Graphics.FillRectangle would
# leave a hard, jagged edge that does not match the rest of the icon.
function Set-Covered {
	param([int]$X, [int]$Y, [double]$Left, [double]$Right, [double]$Top, [double]$Bottom)

	$covX = [Math]::Min($X + 1, $Right) - [Math]::Max($X, $Left)
	$covY = [Math]::Min($Y + 1, $Bottom) - [Math]::Max($Y, $Top)
	if ($covX -le 0 -or $covY -le 0) { return }
	$coverage = $covX * $covY
	if ($coverage -le 0) { return }
	if ($coverage -gt 1) { $coverage = 1 }

	$alpha = [int][Math]::Round($fill.A * $coverage)
	if ($alpha -le 0) { return }

	# Composite the fill over whatever is already there (the stem, mostly), so the join stays opaque and the
	# overlap does not leave a seam.
	$dst = $work.GetPixel($X, $Y)
	$srcA = $alpha / 255.0
	$dstA = $dst.A / 255.0
	$outA = $srcA + $dstA * (1 - $srcA)
	if ($outA -le 0) { $work.SetPixel($X, $Y, [System.Drawing.Color]::FromArgb(0, 0, 0, 0)); return }

	$r = [int][Math]::Round(($fill.R * $srcA + $dst.R * $dstA * (1 - $srcA)) / $outA)
	$gg = [int][Math]::Round(($fill.G * $srcA + $dst.G * $dstA * (1 - $srcA)) / $outA)
	$b = [int][Math]::Round(($fill.B * $srcA + $dst.B * $dstA * (1 - $srcA)) / $outA)
	$work.SetPixel($X, $Y, [System.Drawing.Color]::FromArgb([int][Math]::Round($outA * 255), $r, $gg, $b))
}

function Fill-Rect {
	param([double]$Left, [double]$Right, [double]$Top, [double]$Bottom)
	for ($y = [int][Math]::Floor($Top) - 1; $y -le [int][Math]::Ceiling($Bottom); $y++) {
		for ($x = [int][Math]::Floor($Left) - 1; $x -le [int][Math]::Ceiling($Right); $x++) {
			Set-Covered -X $x -Y $y -Left $Left -Right $Right -Top $Top -Bottom $Bottom
		}
	}
}

# The stem, completed to the O's height. Left edge 74 keeps the source's own anti-aliased column at x73 for the
# rows that already had it; the ideal rectangle starts at 74 so the solid part stays x74..87.
Fill-Rect -Left 74.0 -Right 88.0 -Top 38.0 -Bottom 86.0

# The foot.
Fill-Rect -Left 74.0 -Right 106.0 -Top 74.0 -Bottom 86.0

# --- 3. self-check: the result has to actually be an L, and in one piece ---
#
# These checks exist because earlier versions of this script shipped a glyph that was cut in half and a glyph that
# still had an F's arm, and both had to be reported back as wrong before anyone noticed. Each one below is the
# thing that would have caught it.
$problems = @()

# (a) the stem must exist in EVERY row it spans - a break means an erasing rectangle overlapped it
$stemLeft = 74; $stemRight = 87
$brokenRows = @()
for ($y = 38; $y -le 85; $y++) {
	$solid = 0
	for ($x = $stemLeft; $x -le $stemRight; $x++) { if ($work.GetPixel($x, $y).A -gt 128) { $solid++ } }
	if ($solid -lt ($stemRight - $stemLeft + 1)) { $brokenRows += $y }
}
if ($brokenRows.Count) {
	$problems += ("stem broken at row(s) " + ($brokenRows -join ', ') + " - an erasing rectangle overlaps it")
}

# (b) both arms must be gone to the right of the stem, or it still reads as an F
foreach ($band in $deleteBands) {
	$leftover = 0
	for ($y = $band[0]; $y -le $band[1]; $y++) {
		for ($x = 88; $x -le 108; $x++) { if ($work.GetPixel($x, $y).A -gt 0) { $leftover++ } }
	}
	if ($leftover -gt 0) { $problems += "arm rows $($band[0])..$($band[1]) not fully erased ($leftover px left)" }
}

# (c) the top bar must be gone ABOVE the stem's top, i.e. the glyph must not be wider than the stem up there
$wideTop = @()
for ($y = 38; $y -le 49; $y++) {
	$width = 0
	for ($x = $stemLeft; $x -le 112; $x++) { if ($work.GetPixel($x, $y).A -gt 128) { $width++ } }
	if ($width -gt ($stemRight - $stemLeft + 1)) { $wideTop += $y }
}
if ($wideTop.Count) { $problems += ("rows " + ($wideTop -join ', ') + " are still wider than the stem - that is an F's arm") }

# (d) the foot must exist
$footPx = 0
for ($y = 74; $y -le 85; $y++) {
	for ($x = 88; $x -le 105; $x++) { if ($work.GetPixel($x, $y).A -gt 128) { $footPx++ } }
}
if ($footPx -lt 100) { $problems += "the foot is missing or too small ($footPx px to the right of the stem)" }

$work.Save($Output, [System.Drawing.Imaging.ImageFormat]::Png)
$work.Dispose()

if ($problems.Count) {
	throw ("the result is not a valid L:`n  - " + ($problems -join "`n  - "))
}

Write-Host "[icon] $Source -> $Output"
Write-Host "[icon] deleted top bar and middle bar right of the stem (x88..108); stem completed to y38..85; foot added x74..105 y74..85"
Write-Host "[icon] self-check passed: stem unbroken, both arms erased, no arm above the stem, foot present"
